__title__ = "quat2eul"
__description__ = "Returns the euler angles for the input quaternions"
__version__ = "0.2.0"
__author__ = "Pécheux"
__author_email__ = ""
__license__ = "Apache 2.0"
__url__ = "https://github.com/ClemPech/quaterniontoeuler"
